import Bilza, {IComponent, Ui, CompFactory as cf,PremadeSpriteSheets, hsl} from "./bilza.js";
let bil = new Bilza("bilza", 70);
bil.background.color.set(hsl(240, 100, 85));
const fc = cf.frameCounter();
fc.goto(0, 70, 0);
bil.insert.alwaysOn(fc);
const ss = PremadeSpriteSheets.ghosts("../images/ghosts.png");
ss.xAlign = ss.XAlignOpt.Mid;
ss.yAlign = ss.YAlignOpt.Mid;
ss.x.set(50);
ss.y.set(50);
ss.gotoSpriteName(0, "blue");
ss.gotoSpriteName(2, "greenAlien");
ss.gotoSpriteName(4, "angel");
ss.gotoSpriteName(6, "redDeamon");
ss.gotoSpriteName(8, "robot");
ss.gotoSpriteName(10, "windows");
ss.gotoSpriteName(12, "military");
ss.gotoSpriteName(14, "candy");
ss.gotoSpriteName(16, "chocolate");
ss.gotoSpriteName(18, "cowboy");
ss.gotoSpriteName(20, "bowtie");
ss.gotoSpriteName(22, "wall");
ss.gotoSpriteName(24, "cat");
ss.gotoSpriteName(26, "chinese");
ss.gotoSpriteName(28, "japanese");
ss.gotoSpriteName(30, "kid");
ss.gotoSpriteName(32, "ninja");
ss.gotoSpriteName(34, "pirate");
ss.gotoSpriteName(36, "nurse");
ss.gotoSpriteName(38, "cop");
ss.gotoSpriteName(40, "santa");
ss.gotoSpriteName(42, "queen");
ss.gotoSpriteName(44, "punk");
ss.gotoSpriteName(46, "checker");
ss.gotoSpriteName(48, "stripes");
ss.gotoSpriteName(50, "glasses");
bil.insert.add(ss, 0, 60);
const txt = cf.text("Sprite sheet", hsl(0));
txt.xAlign = txt.XAlignOpt.Mid;
txt.x.set(50);
txt.y.set(80);
txt.width.set(50);
bil.insert.add(txt, 0, 60);
txt.content.goto(0, "blue");
txt.content.goto(2, "greenAlien");
txt.content.goto(4, "angel");
txt.content.goto(6, "redDeamon");
txt.content.goto(8, "robot");
txt.content.goto(10, "windows");
txt.content.goto(12, "military");
txt.content.goto(14, "candy");
txt.content.goto(16, "chocolate");
txt.content.goto(18, "cowboy");
txt.content.goto(20, "bowtie");
txt.content.goto(22, "wall");
txt.content.goto(24, "cat");
txt.content.goto(26, "chinese");
txt.content.goto(28, "japanese");
txt.content.goto(30, "kid");
txt.content.goto(32, "ninja");
txt.content.goto(34, "pirate");
txt.content.goto(36, "nurse");
txt.content.goto(38, "cop");
txt.content.goto(40, "santa");
txt.content.goto(42, "queen");
txt.content.goto(44, "punk");
txt.content.goto(46, "checker");
txt.content.goto(48, "stripes");
txt.content.goto(50, "glasses");
const ui = new Ui(bil);
bil.draw();