import Text from "./text.js";
import lightenDarkenColor from "../../functions/lightenDarkenColor.js";
export default class TextTemplates {
    constructor() {
    }
    h1(duration, endTimeSeconds = Number.MAX_SAFE_INTEGER, content = "Heading One", colorHax = "#000000") {
        let txt = new Text(duration, content, colorHax, 50, 5);
        txt.d.selected = false;
        txt.d.visible = true;
        txt.d.shadowColor = "#b2abab";
        txt.d.shadowOffsetX = 13;
        txt.d.shadowOffsetY = 9;
        txt.d.shadowBlur = 4;
        txt.d.colorBoundingRectangle = "#000000";
        txt.d.flagUseRelativeXY = true;
        txt.d.dynWidth = 80;
        txt.d.dynHeight = 25;
        txt.d.flagUseDynResize = true;
        txt.d.flagShrinkHeightToFit = true;
        txt.d.xAlignment = txt.xAlignmentOptions.Mid;
        txt.d.yAlignment = txt.yAlignmentOptions.Top;
        txt.d.content = content;
        txt.d.padding = 8;
        txt.d.border = 4;
        txt.d.colorBorder = colorHax;
        txt.d.colorBg = lightenDarkenColor(colorHax, 245);
        txt.d.color = colorHax;
        txt.d.fontSize = 26;
        txt.d.showContent = true;
        txt.d.showBg = true;
        txt.d.showTextShadow = false;
        txt.d.showBgShadow = false;
        txt.d.showBorderShadow = false;
        txt.d.maxDisplayChars = 200;
        return txt;
    }
    jt(duration, endTimeSeconds = Number.MAX_SAFE_INTEGER, content = "JUMBO TRON", colorHax = "#008000") {
        let txt = new Text(duration, content, colorHax);
        txt.d.x = 50;
        txt.d.y = 50;
        txt.d.selected = false;
        txt.d.visible = true;
        txt.d.shadowColor = "#b2abab";
        txt.d.shadowOffsetX = 13;
        txt.d.shadowOffsetY = 9;
        txt.d.shadowBlur = 4;
        txt.d.colorBoundingRectangle = "#000000";
        txt.d.xAlignment = txt.xAlignmentOptions.Mid;
        txt.d.yAlignment = txt.yAlignmentOptions.Mid;
        txt.d.content = content;
        txt.d.padding = 20;
        txt.d.border = 10;
        txt.d.dynWidth = 80;
        txt.d.dynHeight = 100;
        txt.d.colorBorder = colorHax;
        txt.d.colorBg = lightenDarkenColor(colorHax, 245);
        txt.d.color = colorHax;
        txt.d.fontSize = 45;
        txt.d.showContent = true;
        txt.d.showBg = true;
        txt.d.showTextShadow = true;
        txt.d.showBgShadow = true;
        txt.d.showBorderShadow = false;
        txt.d.maxDisplayChars = 200;
        txt.d.flagUseDynResize = true;
        txt.d.flagShrinkHeightToFit = true;
        txt.d.flagUseRelativeXY = true;
        return txt;
    }
    lb(duration, endTimeSeconds = Number.MAX_SAFE_INTEGER, content = "Left Bottom", colorHax = "#008000") {
        let txt = new Text(duration, content, colorHax);
        txt.d.x = 0;
        txt.d.y = 100;
        txt.d.selected = false;
        txt.d.visible = true;
        txt.d.shadowColor = "#b2abab";
        txt.d.shadowOffsetX = 13;
        txt.d.shadowOffsetY = 9;
        txt.d.shadowBlur = 4;
        txt.d.colorBoundingRectangle = "#000000";
        txt.d.xAlignment = txt.xAlignmentOptions.Left;
        txt.d.yAlignment = txt.yAlignmentOptions.Bot;
        txt.d.content = content;
        txt.d.padding = 5;
        txt.d.border = 0;
        txt.d.dynWidth = 20;
        txt.d.dynHeight = 200;
        txt.d.colorBorder = colorHax;
        txt.d.colorBg = lightenDarkenColor(colorHax, 245);
        txt.d.color = colorHax;
        txt.d.fontSize = 45;
        txt.d.showContent = true;
        txt.d.showBg = true;
        txt.d.showTextShadow = false;
        txt.d.showBgShadow = false;
        txt.d.showBorderShadow = false;
        txt.d.maxDisplayChars = 200;
        txt.d.flagUseDynResize = true;
        txt.d.flagShrinkHeightToFit = true;
        txt.d.flagUseRelativeXY = true;
        return txt;
    }
    lm(duration, endTimeSeconds = Number.MAX_SAFE_INTEGER, content = "Left Mid", colorHax = "#008000") {
        let txt = new Text(duration, content, colorHax);
        txt.d.x = 0;
        txt.d.y = 50;
        txt.d.selected = false;
        txt.d.visible = true;
        txt.d.shadowColor = "#b2abab";
        txt.d.shadowOffsetX = 13;
        txt.d.shadowOffsetY = 9;
        txt.d.shadowBlur = 4;
        txt.d.colorBoundingRectangle = "#000000";
        txt.d.xAlignment = txt.xAlignmentOptions.Left;
        txt.d.yAlignment = txt.yAlignmentOptions.Mid;
        txt.d.content = content;
        txt.d.padding = 5;
        txt.d.border = 0;
        txt.d.dynWidth = 20;
        txt.d.dynHeight = 200;
        txt.d.colorBorder = colorHax;
        txt.d.colorBg = lightenDarkenColor(colorHax, 245);
        txt.d.color = colorHax;
        txt.d.fontSize = 45;
        txt.d.showContent = true;
        txt.d.showBg = true;
        txt.d.showTextShadow = false;
        txt.d.showBgShadow = false;
        txt.d.showBorderShadow = false;
        txt.d.maxDisplayChars = 200;
        txt.d.flagUseDynResize = true;
        txt.d.flagShrinkHeightToFit = true;
        txt.d.flagUseRelativeXY = true;
        return txt;
    }
    lt(duration, endTimeSeconds = Number.MAX_SAFE_INTEGER, content = "Left Top", colorHax = "#008000") {
        let txt = new Text(duration, content, colorHax);
        txt.d.x = 0;
        txt.d.y = 0;
        txt.d.selected = false;
        txt.d.visible = true;
        txt.d.shadowColor = "#b2abab";
        txt.d.shadowOffsetX = 13;
        txt.d.shadowOffsetY = 9;
        txt.d.shadowBlur = 4;
        txt.d.colorBoundingRectangle = "#000000";
        txt.d.xAlignment = txt.xAlignmentOptions.Left;
        txt.d.yAlignment = txt.yAlignmentOptions.Top;
        txt.d.content = content;
        txt.d.padding = 5;
        txt.d.border = 0;
        txt.d.dynWidth = 20;
        txt.d.dynHeight = 200;
        txt.d.colorBorder = colorHax;
        txt.d.colorBg = lightenDarkenColor(colorHax, 245);
        txt.d.color = colorHax;
        txt.d.fontSize = 45;
        txt.d.showContent = true;
        txt.d.showBg = true;
        txt.d.showTextShadow = false;
        txt.d.showBgShadow = false;
        txt.d.showBorderShadow = false;
        txt.d.maxDisplayChars = 200;
        txt.d.flagUseDynResize = true;
        txt.d.flagShrinkHeightToFit = true;
        txt.d.flagUseRelativeXY = true;
        return txt;
    }
    rb(duration, endTimeSeconds = Number.MAX_SAFE_INTEGER, content = "Right Bottom", colorHax = "#008000") {
        let txt = new Text(duration, content, colorHax);
        txt.d.x = 100;
        txt.d.y = 100;
        txt.d.selected = false;
        txt.d.visible = true;
        txt.d.shadowColor = "#b2abab";
        txt.d.shadowOffsetX = 13;
        txt.d.shadowOffsetY = 9;
        txt.d.shadowBlur = 4;
        txt.d.colorBoundingRectangle = "#000000";
        txt.d.xAlignment = txt.xAlignmentOptions.Right;
        txt.d.yAlignment = txt.yAlignmentOptions.Bot;
        txt.d.content = content;
        txt.d.padding = 5;
        txt.d.border = 0;
        txt.d.dynWidth = 20;
        txt.d.dynHeight = 200;
        txt.d.colorBorder = colorHax;
        txt.d.colorBg = lightenDarkenColor(colorHax, 245);
        txt.d.color = colorHax;
        txt.d.fontSize = 45;
        txt.d.showContent = true;
        txt.d.showBg = true;
        txt.d.showTextShadow = false;
        txt.d.showBgShadow = false;
        txt.d.showBorderShadow = false;
        txt.d.maxDisplayChars = 200;
        txt.d.flagUseDynResize = true;
        txt.d.flagShrinkHeightToFit = true;
        txt.d.flagUseRelativeXY = true;
        return txt;
    }
    rm(duration, endTimeSeconds = Number.MAX_SAFE_INTEGER, content = "Right Mid", colorHax = "#008000") {
        let txt = new Text(duration, content, colorHax);
        txt.d.x = 100;
        txt.d.y = 50;
        txt.d.selected = false;
        txt.d.visible = true;
        txt.d.shadowColor = "#b2abab";
        txt.d.shadowOffsetX = 13;
        txt.d.shadowOffsetY = 9;
        txt.d.shadowBlur = 4;
        txt.d.colorBoundingRectangle = "#000000";
        txt.d.xAlignment = txt.xAlignmentOptions.Right;
        txt.d.yAlignment = txt.yAlignmentOptions.Mid;
        txt.d.content = content;
        txt.d.padding = 5;
        txt.d.border = 0;
        txt.d.dynWidth = 20;
        txt.d.dynHeight = 200;
        txt.d.colorBorder = colorHax;
        txt.d.colorBg = lightenDarkenColor(colorHax, 245);
        txt.d.color = colorHax;
        txt.d.fontSize = 45;
        txt.d.showContent = true;
        txt.d.showBg = true;
        txt.d.showTextShadow = false;
        txt.d.showBgShadow = false;
        txt.d.showBorderShadow = false;
        txt.d.maxDisplayChars = 200;
        txt.d.flagUseDynResize = true;
        txt.d.flagShrinkHeightToFit = true;
        txt.d.flagUseRelativeXY = true;
        return txt;
    }
    rt(duration, endTimeSeconds = Number.MAX_SAFE_INTEGER, content = "Right Top", colorHax = "#008000") {
        let txt = new Text(duration, content, colorHax);
        txt.d.x = 100;
        txt.d.y = 0;
        txt.d.selected = false;
        txt.d.visible = true;
        txt.d.shadowColor = "#b2abab";
        txt.d.shadowOffsetX = 13;
        txt.d.shadowOffsetY = 9;
        txt.d.shadowBlur = 4;
        txt.d.colorBoundingRectangle = "#000000";
        txt.d.xAlignment = txt.xAlignmentOptions.Right;
        txt.d.yAlignment = txt.yAlignmentOptions.Top;
        txt.d.content = content;
        txt.d.padding = 5;
        txt.d.border = 0;
        txt.d.dynWidth = 20;
        txt.d.dynHeight = 200;
        txt.d.colorBorder = colorHax;
        txt.d.colorBg = lightenDarkenColor(colorHax, 245);
        txt.d.color = colorHax;
        txt.d.fontSize = 45;
        txt.d.showContent = true;
        txt.d.showBg = true;
        txt.d.showTextShadow = false;
        txt.d.showBgShadow = false;
        txt.d.showBorderShadow = false;
        txt.d.maxDisplayChars = 200;
        txt.d.flagUseDynResize = true;
        txt.d.flagShrinkHeightToFit = true;
        txt.d.flagUseRelativeXY = true;
        return txt;
    }
    mt(duration, endTimeSeconds = Number.MAX_SAFE_INTEGER, content = "Mid Top", colorHax = "#008000") {
        let txt = new Text(duration, content, colorHax);
        txt.d.x = 50;
        txt.d.y = 0;
        txt.d.selected = false;
        txt.d.visible = true;
        txt.d.shadowColor = "#b2abab";
        txt.d.shadowOffsetX = 13;
        txt.d.shadowOffsetY = 9;
        txt.d.shadowBlur = 4;
        txt.d.colorBoundingRectangle = "#000000";
        txt.d.xAlignment = txt.xAlignmentOptions.Mid;
        txt.d.yAlignment = txt.yAlignmentOptions.Top;
        txt.d.content = content;
        txt.d.padding = 5;
        txt.d.border = 0;
        txt.d.dynWidth = 20;
        txt.d.dynHeight = 200;
        txt.d.colorBorder = colorHax;
        txt.d.colorBg = lightenDarkenColor(colorHax, 245);
        txt.d.color = colorHax;
        txt.d.fontSize = 45;
        txt.d.showContent = true;
        txt.d.showBg = true;
        txt.d.showTextShadow = false;
        txt.d.showBgShadow = false;
        txt.d.showBorderShadow = false;
        txt.d.maxDisplayChars = 200;
        txt.d.flagUseDynResize = true;
        txt.d.flagShrinkHeightToFit = true;
        txt.d.flagUseRelativeXY = true;
        return txt;
    }
    mm(duration, endTimeSeconds = Number.MAX_SAFE_INTEGER, content = "Mid Mid", colorHax = "#008000") {
        let txt = new Text(duration, content, colorHax);
        txt.d.x = 50;
        txt.d.y = 50;
        txt.d.selected = false;
        txt.d.visible = true;
        txt.d.shadowColor = "#b2abab";
        txt.d.shadowOffsetX = 13;
        txt.d.shadowOffsetY = 9;
        txt.d.shadowBlur = 4;
        txt.d.colorBoundingRectangle = "#000000";
        txt.d.xAlignment = txt.xAlignmentOptions.Mid;
        txt.d.yAlignment = txt.yAlignmentOptions.Mid;
        txt.d.content = content;
        txt.d.padding = 5;
        txt.d.border = 0;
        txt.d.dynWidth = 20;
        txt.d.dynHeight = 200;
        txt.d.colorBorder = colorHax;
        txt.d.colorBg = lightenDarkenColor(colorHax, 245);
        txt.d.color = colorHax;
        txt.d.fontSize = 45;
        txt.d.showContent = true;
        txt.d.showBg = true;
        txt.d.showTextShadow = false;
        txt.d.showBgShadow = false;
        txt.d.showBorderShadow = false;
        txt.d.maxDisplayChars = 200;
        txt.d.flagUseDynResize = true;
        txt.d.flagShrinkHeightToFit = true;
        txt.d.flagUseRelativeXY = true;
        return txt;
    }
    mb(duration, endTimeSeconds = Number.MAX_SAFE_INTEGER, content = "Mid Bottom", colorHax = "#008000") {
        let txt = new Text(duration, content, colorHax);
        txt.d.x = 50;
        txt.d.y = 100;
        txt.d.selected = false;
        txt.d.visible = true;
        txt.d.shadowColor = "#b2abab";
        txt.d.shadowOffsetX = 13;
        txt.d.shadowOffsetY = 9;
        txt.d.shadowBlur = 4;
        txt.d.colorBoundingRectangle = "#000000";
        txt.d.xAlignment = txt.xAlignmentOptions.Mid;
        txt.d.yAlignment = txt.yAlignmentOptions.Bot;
        txt.d.content = content;
        txt.d.padding = 5;
        txt.d.border = 0;
        txt.d.dynWidth = 20;
        txt.d.dynHeight = 200;
        txt.d.colorBorder = colorHax;
        txt.d.colorBg = lightenDarkenColor(colorHax, 245);
        txt.d.color = colorHax;
        txt.d.fontSize = 45;
        txt.d.showContent = true;
        txt.d.showBg = true;
        txt.d.showTextShadow = false;
        txt.d.showBgShadow = false;
        txt.d.showBorderShadow = false;
        txt.d.maxDisplayChars = 200;
        txt.d.flagUseDynResize = true;
        txt.d.flagShrinkHeightToFit = true;
        txt.d.flagUseRelativeXY = true;
        return txt;
    }
    bulletPointMid(duration, endTimeSeconds = Number.MAX_SAFE_INTEGER, content = "bulletPointMid", colorHax = "#008000", y = 50) {
        let txt = new Text(duration, content, colorHax, 50, y);
        txt.d.selected = false;
        txt.d.visible = true;
        txt.d.shadowColor = "#b2abab";
        txt.d.shadowOffsetX = 13;
        txt.d.shadowOffsetY = 9;
        txt.d.shadowBlur = 4;
        txt.d.colorBoundingRectangle = "#000000";
        txt.d.xAlignment = txt.xAlignmentOptions.Mid;
        txt.d.yAlignment = txt.yAlignmentOptions.Mid;
        txt.d.content = content;
        txt.d.padding = 20;
        txt.d.border = 0;
        txt.d.dynWidth = 80;
        txt.d.dynHeight = 30;
        txt.d.colorBorder = colorHax;
        txt.d.colorBg = lightenDarkenColor(colorHax, 245);
        txt.d.color = colorHax;
        txt.d.fontSize = 45;
        txt.d.showContent = true;
        txt.d.showBg = true;
        txt.d.showTextShadow = false;
        txt.d.showBgShadow = false;
        txt.d.showBorderShadow = false;
        txt.d.maxDisplayChars = 200;
        txt.d.flagUseDynResize = true;
        txt.d.flagShrinkHeightToFit = true;
        txt.d.flagUseRelativeXY = true;
        return txt;
    }
}
