import BaseTest from "./baseTest.js";
import Bilza, { CompFactory as cf } from "../bilza.js";
const bil = new Bilza("bilza");
bil.resizeCanvas(1000, 500);
const tst = new BaseTest("Non Responsive Test");
const fill = cf.fillRect("green");
fill.responsivePadding = false;
fill.responsiveDims = false;
tst.toNotThrow(() => { fill.contentWidth(); });
fill.width.set(10);
fill.paddingLeft.set(10);
fill.paddingRight.set(10);
fill.paddingTop.set(10);
fill.paddingBottom.set(10);
bil.insert.add(fill, 0, 60);
bil.init();
tst.toEqual(fill.contentWidth(), 10);
tst.toEqual(fill.compWidth(), 30);
fill.border.set(10);
tst.toEqual(fill.compWidth(), 50);
fill.height.set(10);
tst.toEqual(fill.compHeight(), 50);
