import BaseTest from "./baseTest.js";
import Bilza, { CompFactory as cf } from "../bilza.js";
const bil = new Bilza("bilza");
bil.resizeCanvas(1000, 500);
const tst = new BaseTest("responsive Test");
const fill = cf.fillRect("green");
fill.responsivePadding = true;
fill.responsiveDims = true;
tst.toThrow(() => { fill.contentWidth(); }, "The component is not initialized yet");
bil.insert.add(fill, 0, 60);
bil.init();
fill.width.set(10);
fill.paddingLeft.set(10);
fill.paddingRight.set(10);
fill.paddingTop.set(10);
fill.paddingBottom.set(10);
bil.init();
tst.toEqual(fill.contentWidth(), 100);
tst.toEqual(fill.compWidth(), 300);
fill.border.set(10);
tst.toEqual(fill.compWidth(), 320);
fill.height.set(10);
tst.toEqual(fill.compHeight(), 170);
