import BaseTest from "./baseTest.js";
import Bilza, { CompFactory as cf } from "../bilza.js";
const bil = new Bilza("bilza");
bil.resizeCanvas(1000, 500);
const tst = new BaseTest(" Text Test ");
const fill = cf.text("Text Test");
fill.responsivePadding = true;
fill.responsiveDims = true;
fill.responsiveCoordinates = true;
fill.x.set(0);
fill.y.set(0);
fill.width.set(10);
fill.height.set(10);
fill.paddingLeft.set(10);
fill.paddingRight.set(10);
fill.paddingTop.set(10);
fill.paddingBottom.set(10);
fill.border.set(10);
bil.insert.add(fill, 0, 60);
bil.init();
bil.draw();
tst.approxEqual(fill.compWidth(), 320, 5, "compWidth after draw/update");
tst.isLessThan(fill.compHeight(), 170, "compHeight after draw/update");
fill.xAlign = fill.XAlignOpt.Mid;
fill.yAlign = fill.YAlignOpt.Mid;
tst.toEqual(fill.xAligned(), -159, "xAligned.Mid");
tst.isGreaterThan(fill.yAligned(), -86, "yAligned.Mid");
fill.xAlign = fill.XAlignOpt.Right;
fill.yAlign = fill.YAlignOpt.Bot;
tst.toEqual(fill.xAligned(), -318, "XAlignOpt.Right");
tst.isLessThan(fill.yAligned(), -86, "YAlignOpt.Bot");
