import Bilza from "../Bilza.js";
import TestComp from "../testComp/testComp.js";
let bil = new Bilza("bilza");
let tst = new TestComp("New");
tst.duration = 60;
tst.p.x.animate(2, 10, 0, 300);
tst.p.y.animate(2, 10, 0, 300);
bil.insert.append(tst, tst.duration);
bil.init();
bil.start();
