import Bilza, { Ui, CompFactory as cf } from "../bilza.js";
let bil = new Bilza("bilza", 70);
const g = cf.grid();
bil.insert.alwaysOn(g);
const counter = cf.frameCounter("#ff0000");
counter.goto(0, 90, 0);
bil.insert.alwaysOn(counter);
const plain = cf.line();
plain.color.set("#008000");
plain.y2.animate(0, 10, 10, 100);
plain.lineWidth.animate(0, 10, 0, 100);
bil.insert.add(plain, 0, 15);
const ui = new Ui(bil);
bil.draw();
