import First from "../corecomps/first.js";
import Bilzaa2d from "../bilzaa2d/bilzaa2d.js";
let b = new Bilzaa2d();
let f = new First();
let tr = f.newStyleTransition();
tr.frameStart = 4;
tr.fontSize = 330;
b.add_comp(f);
console.log("b", b);
b.start();
