import Bilza, { XAlignment, YAlignment, CompFactory as cf } from "../Bilza.js";
let bil = new Bilza("bilza");
bil.resizeCanvas(1000, 400);
let grid = cf.grid();
bil.insert.alwaysOn(grid);
let tst = cf.rect();
tst.duration = 600;
tst.p.dynWidth.animate(0, 2, 10, 20);
tst.p.loc.animate(5, 8, 0, 50, 0, 50, XAlignment.Left, XAlignment.Mid, YAlignment.Top, YAlignment.Mid);
bil.insert.append(tst, tst.duration);
bil.init();
bil.start();
