import Bilza, { CompFactory as cf } from "../Bilza.js";
let bil = new Bilza("bilza");
bil.resizeCanvas(1000, 400);
let grid = cf.grid();
bil.insert.alwaysOn(grid);
let hdg = cf.text("Main Heading", "#008000");
hdg.showBg = true;
hdg.border = 5;
hdg.colorBorder = "yellow";
hdg.colorBg = "#008000";
hdg.color = "#ff0000";
hdg.loc.goto(0, 0, 0);
hdg.duration = 600;
bil.insert.append(hdg, hdg.duration);
bil.init();
bil.start();
