import Bilza from "../Bilza.js";
import TestComp from "../../src/testComp/testComp.js";
let bil = new Bilza("bilza");
let tst = new TestComp("ok");
tst.duration = 20;
tst.p.x.setValue(0);
tst.moveX(2, 10, tst.offScreenXOpt.XLeft, tst.offScreenXOpt.XRight);
tst.moveX(11, 20, tst.offScreenXOpt.XRight, tst.offScreenXOpt.XLeft);
tst.moveX(21, 30, tst.offScreenXOpt.XLeft, tst.offScreenXOpt.XRight);
tst.moveX(31, 40, tst.offScreenXOpt.XRight, tst.offScreenXOpt.XLeft);
bil.insert.append(tst, tst.duration);
bil.init();
bil.start();
