export var FontFamily;
(function (FontFamily) {
    FontFamily["Arial"] = "Arial";
    FontFamily["ArialBlack"] = "Arial Black";
    FontFamily["Verdana"] = "Verdana";
    FontFamily["Tahoma"] = "Tahoma";
    FontFamily["Impact"] = "Impact";
    FontFamily["Times"] = "Times";
    FontFamily["Helvetica"] = "Helvetica";
    FontFamily["TimesNewRoman"] = "Times New Roman";
    FontFamily["Didot"] = "Didot";
    FontFamily["Calibri"] = "Calibri";
    FontFamily["Georgia"] = "Georgia";
    FontFamily["AmericanTypewriter"] = "American Typewriter";
    FontFamily["Courier"] = "Courier";
    FontFamily["CourierNew"] = "Courier New";
    FontFamily["LucidaConsole"] = "Lucida Console";
    FontFamily["Monaco"] = "Monaco";
    FontFamily["BradleyHand"] = "Bradley Hand";
    FontFamily["BrushScriptMT"] = "Brush Script MT";
    FontFamily["BrushScript"] = "Brush Script";
    FontFamily["Luminari"] = "Luminari";
})(FontFamily || (FontFamily = {}));
