import { DrawLayer } from "../bilza.js";
import { AniNumber, AniBoolean, AniColor } from "../animationModule/animations.js";
import Style from "../design/style.js";
import { XAlignOpt } from "./designBC/xAlignOpt.js";
import { YAlignOpt } from "./designBC/yAlignOpt.js";
export default class BaseComponentBase {
    protected xAlign: XAlignOpt;
    protected yAlign: YAlignOpt;
    protected xRotate: XAlignOpt;
    protected yRotate: YAlignOpt;
    protected readonly XAlignOpt: typeof XAlignOpt;
    protected readonly YAlignOpt: typeof YAlignOpt;
    readonly id: string;
    private interactive;
    drawLayer: DrawLayer;
    protected style: Style;
    alwaysOn: boolean;
    readonly version: string;
    visible: AniBoolean;
    rotation: AniNumber;
    opacity: AniNumber;
    color: AniColor;
    width: AniNumber;
    height: AniNumber;
    selected: boolean;
    border: AniNumber;
    colorBorder: AniColor;
    borderContentArea: AniNumber;
    colorContentAreaBorder: AniColor;
    paddingTop: AniNumber;
    paddingBottom: AniNumber;
    paddingRight: AniNumber;
    paddingLeft: AniNumber;
    x: AniNumber;
    y: AniNumber;
    colorBackground: AniColor;
    showBackground: AniBoolean;
    constructor();
}
//# sourceMappingURL=99BaseComponentBase.d.ts.map