import { Style, Pack, IComponent, DrawLayer, Transition } from "../Bilza.js";
import CompDataBase from "./CompDataBase.js";
import { XAlignment } from "./xAlignment.js";
import { YAlignment } from "./yAlignment.js";
import { DisplayTypeOptions } from "./displayTypeOptions.js";
export default class Component<T extends CompDataBase> implements IComponent {
    protected compData: Transition<T>;
    d: T;
    data: T;
    readonly id: string;
    drawLayer: DrawLayer;
    protected msStart: number;
    style: Style;
    xAlignmentOptions: typeof XAlignment;
    yAlignmentOptions: typeof YAlignment;
    displayTypeOptions: typeof DisplayTypeOptions;
    displayType: DisplayTypeOptions;
    duration: number;
    protected startTime: number;
    constructor(DataFn: () => T);
    width(p: Pack): number;
    height(p: Pack): number;
    init(p: Pack): boolean;
    draw(p: Pack): boolean;
    update(msDelta: number, p: Pack): boolean;
    log(msg: string): void;
    addTransition(msStart: number): T;
    checkCollision(x: number, y: number, p: Pack): boolean;
    shadowsOff(): void;
    setShadow(shadowBlur?: number, shadowOffsetX?: number, shadowOffsetY?: number, shadowColor?: string): void;
    shadowsOn(): void;
    resize(width: number, height: number): number;
    drawBoundingRectangle(p: Pack): boolean;
    applyTransition(msDelta: number): void;
    protected xAfterAlignment(p: Pack): number;
    protected yAfterAlignment(p: Pack): number;
    getEndTime(inMilliSec?: boolean): number;
    getStartTime(inMilliSec?: boolean): number;
}
//# sourceMappingURL=component.d.ts.map