export var FontNames;
(function (FontNames) {
    FontNames["Arial"] = "Arial";
    FontNames["ArialBlack"] = "Arial Black";
    FontNames["Verdana"] = "Verdana";
    FontNames["Tahoma"] = "Tahoma";
    FontNames["Impact"] = "Impact";
    FontNames["Times"] = "Times";
    FontNames["Helvetica"] = "Helvetica";
    FontNames["TimesNewRoman"] = "Times New Roman";
    FontNames["Didot"] = "Didot";
    FontNames["Calibri"] = "Calibri";
    FontNames["Georgia"] = "Georgia";
    FontNames["AmericanTypewriter"] = "American Typewriter";
    FontNames["Courier"] = "Courier";
    FontNames["CourierNew"] = "Courier New";
    FontNames["LucidaConsole"] = "Lucida Console";
    FontNames["Monaco"] = "Monaco";
    FontNames["BradleyHand"] = "Bradley Hand";
    FontNames["BrushScriptMT"] = "Brush Script MT";
    FontNames["BrushScript"] = "Brush Script";
    FontNames["Luminari"] = "Luminari";
})(FontNames || (FontNames = {}));
