import Bilza, { Ui, CompFactory as cf } from "./bilza.js";
let bil = new Bilza("bilza", 70);
const grid = cf.grid("grey");
grid.goto(0, 90, 0);
bil.insert.alwaysOn(grid);
const txt = cf.fillRect("green");
txt.width.set(20);
txt.height.set(20);
txt.paddingLeft.set(50);
txt.showBackground.set(true);
txt.colorBackground.set("pink");
txt.goto(0, 10, 50);
bil.insert.add(txt, 0, 50);
const ui = new Ui(bil);
bil.draw();
