import Bilza, { Ui, CompFactory as cf } from "./bilza.js";
let bil = new Bilza("bilza", 70);
const counter = cf.grid();
counter.colorHorizontalLines = "red";
bil.insert.alwaysOn(counter);
const txt01 = cf.text("Before Append");
txt01.color.set("red");
bil.insert.add(txt01, 0, 5);
const ui = new Ui(bil);
bil.draw();
