import Bilza, { Ui, CompFactory as cf } from "./bilza.js";
let bil = new Bilza("bilza", 70);
const g = cf.grid();
bil.insert.alwaysOn(g);
const counter = cf.frameCounter("#ff0000");
counter.goto(0, 90, 0);
bil.insert.alwaysOn(counter);
const plain = cf.fillRect("green");
bil.insert.add(plain, 0, 20);
const ui = new Ui(bil);
bil.draw();
