import Bilza, { Ui, CompFactory as cf } from "./bilza.js";
let bil = new Bilza("bilza", 70);
const g = cf.grid();
bil.insert.alwaysOn(g);
const hdg = cf.text("Particle System", "red");
hdg.colorBorder.set("blue");
hdg.x.setInitValue(50);
hdg.y.setInitValue(50);
hdg.xAlign = hdg.XAlignOpt.Mid;
hdg.yAlign = hdg.YAlignOpt.Mid;
hdg.width.set(30);
hdg.border.animate(0, 5, 0, 20);
hdg.rotation.animate(6, 20, 0, 2000);
bil.insert.add(hdg, 0, 60);
const ui = new Ui(bil);
bil.draw();
